name:                HaskellProgramming
version:             0.1.0
github:              "wanggang1/HaskellProgramming"
license:             BSD3
author:              "Gang Wang"
maintainer:          "gwgs.github@gmail.com"
copyright:           "2019 Gang Wang"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/wanggang1/HaskellProgramming#readme>

custom-setup:
  dependencies:
  - base
  - Cabal
  - cabal-doctest >=1.0.2 && <1.1

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- checkers

ghc-options:
- -Wall
- -fwarn-tabs

library:
  source-dirs:     exercises
  exposed-modules: CH18.Exercises
  other-modules:   CH16.Nat

executables:
  hp:
    main:              Main.hs
    source-dirs:       src
    other-modules:     HP.Ch18
    dependencies:
    - HaskellProgramming
    - gps
    - time
    - split
    - containers
